### ISSUE TITLE
Why aren't you using the Size class in android.util package

### ISSUE THREAD

**Issue by ChristopheCVB** [yqritc/Android-ScalableVideoView#13]
The class Size already exists in the Android package `android.util.Size`

http://developer.android.com/reference/android/util/Size.html

I'll try do make a PR if you're not planning to do it and agree ;)

**Comment by yqritc** [comment]
@ChristopheCVB 
this is because size class is added in API level 21.
min sdk version of this library is 14.

**Comment by ChristopheCVB** [comment]
Yeah, my bad :/
