### ISSUE TITLE
Android Studio Compile Error

### ISSUE THREAD

**Issue by simongiesen** [yqritc/Android-ScalableVideoView#14]
Hi,

Android Studio is not going to compile and run, any suggestions?

Warning:Dependency org.apache.httpcomponents:httpclient:4.5.1 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency org.apache.httpcomponents:httpclient:4.5.1 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages

Error:Execution failed for task ':sample:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by yqritc** [comment]
@simongiesen 
Are u running my sample project?
or this error occurs in ur project?

**Comment by simongiesen** [comment]
Sample Project, clean out of the box

**Comment by yqritc** [comment]
I run sample and it's fine.
I believe something is wrong in ur environment.
clean and rebuild the project.
