### ISSUE TITLE
is it possible to playing the specific frame?

### ISSUE THREAD

**Issue by waikchiu5** [yqritc/Android-ScalableVideoView#17]
I wan to create a function to playing the video as GIFs.
For example, the length of the video is 2 second (fixed). The frame rate is 12/s. Total frame is 24.
When i clicked the button, the scalableVideoView will show no.10 frame.

**Comment by yqritc** [comment]
@waikchiu5 
Sorry for late response.
Unfortunately this library does not have its functionality.
Android 6.0 added [PlaybackParams](https://developer.android.com/reference/android/media/PlaybackParams.html) for MediaPlayer, so u may be able to use it.
