### ISSUE TITLE
No Way to set a Uri for a video stored in Sdcard ...

### ISSUE THREAD

**Issue by iAviatorJose** [yqritc/Android-ScalableVideoView#2]

**Comment by yqritc** [comment]
thanks for your request. i'll add its interface as soon as possible.

**Comment by yqritc** [comment]
Added interface for path, uri as data source for ver1.0.1

**Comment by bhuvneshvarma** [comment]
I tried using below code for playing video from external storage but its not working..
            contentVideoView.setDataSource(context,Uri.parse(Environment.getExternalStorageDirectory() + "/demo.mp4"));
           contentVideoView.start();
            contentVideoView.setLooping(true);

**Comment by chanoo** [comment]
videoView.prepareAsync();
