### ISSUE TITLE
video has gray border around it in Android 6.

### ISSUE THREAD

**Issue by shumin0809** [yqritc/Android-ScalableVideoView#8]
Hi,

It's a great library :). I recently used it to scale my video. It works perfectly in Android5. However, in android 6, my video always has a gray border. 
Here's my code:

<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    >
    <com.yqritc.scalablevideoview.ScalableVideoView
        android:id="@+id/video_view"
        android:layout_width="200dp"
        android:layout_height="100dp"
        android:layout_centerInParent="true"
        app:scalableType="centerCrop"
        />
</RelativeLayout>

Since my parent background is white, the gray border of the video looks ugly right now. Could you please help me with that ? Thanks. :)

**Comment by yqritc** [comment]
@shumin0809 
I checked sample project by Android 6.
but I could not see gray border.
do u see gray border when you run my sample project?
