### ISSUE TITLE
Problem with ScalableVideoView in Recycler view

### ISSUE THREAD

**Issue by depodefi** [yqritc/Android-ScalableVideoView#9]
I noticed problem while checking out demo of your library on Google Play Store. I was using Nexus 5X with Android 6.0 on board. The problem I noticed happened with video list - RecyclerView in this case. While scrolling up and down for some row display black view instead of video view. Please refer to attached screenshots.

![screenshot_20151108-215532](https://cloud.githubusercontent.com/assets/5682491/11022673/a1bf034c-8664-11e5-877f-5d80429e0903.png)
![screenshot_20151108-215540](https://cloud.githubusercontent.com/assets/5682491/11022672/a1b644d2-8664-11e5-924b-12de73658b7a.png)

**Comment by depodefi** [comment]
I found some relevant informations that this might be an Android 6.0 issue. some more info here: https://code.google.com/p/android/issues/detail?id=191218&q=label%3APriority-Medium&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars so I guess issue can be closed

**Comment by MrNovado** [comment]
Same in android 4.4; sometimes video does not load (start) currectly, - scrolling video from viewport and back sometimes forces video to restart, but sometimes it does not happen.

At first glance it seems an issue either with recyclerView or sampleAdapter: scrolling videoView from viewport stops video from playing, but scrolling back not necessarily hits onBindViewHolder.

**Comment by depodefi** [comment]
Did you found any workaround for this issue? Using RecyclerView support lib in version 23.1.1 problem still exists.

**Comment by MrNovado** [comment]
2depodefi: Unfortunately right now I don't have the time to play around with this one: I ended up using sprylab's textureVideoView (which I found more stable at the moment) and implementing scalability into that. I made my own adapter and it seems to work just fine.

**Comment by yqritc** [comment]
@depodefi 
Sorry for late replay.
I reproduced the problem and fixed it.
The problem is that bindViewHolder is not always called when scrolling although the item view is detached from the window.
So, I fixed the problem and published ver 1.0.2.
An app on google play should be updated soon, so please check if you are still interested in it.
